### ISSUE TITLE
Automatic deployment to staging of master branch

### ISSUE THREAD

**Issue by connorkrupp** [mhacks/mhacks-web#103]
### Expected function
Upon merge of commit into master branch, staging should automatically reflect the master branch

**Comment by antoniomika** [comment]
I kinda like the idea of integrating this with the mhacks backend. My thought is to use something like https://github.com/steelbrain/node-ssh in combination with the simplicity of the docker scripts to easily do a update. The only other thing we have to think of are environment variables and how to deploy them.
