### ISSUE TITLE
Announcement Route

### ISSUE THREAD

**Issue by connorkrupp** [mhacks/mhacks-web#106]
#### GET /v1/announcements
Default implementation (if user not logged in or doesn't have more permissions):
should return all approved announcements that have "broadcastAt" before the current date sorted most recent first
If user has permission: "can_edit_announcement"
return all of them

support `since=_date_` and `until=_date_` to filter results

#### POST /v1/announcements
if user doesn't have permission or if fields aren't there: reject with appropriate status and message
if user has permission ^:
create new announcement with the fields in HTTP body

#### PUT/PATCH /v1/announcements
update announcement conforming to PUT or PATCH semantics

**Comment by connorkrupp** [comment]
@antoniomika We should probably clarify how we want to handle client caching and how it relates to models. I assume we want to support query parameters such as `since=_date_` and `until=_date_`? 

Should we have if something is deleted should we set deleted=true on model instance and in a GET request that contains a `since` or `until` include deleted instances with just an object like `{id: foo, deleted: true}`?

**Comment by antoniomika** [comment]
@connorkrupp How often are these datatypes repulled from the server? We could do that or we could just use etags and invalidate cache so all things need to be fetched. I don't think we have to worry as much about caching tbh. And yes, `since, until` pagination keys should be used with unix timestamps

**Comment by connorkrupp** [comment]
Also we need to get permissions working probs

**Comment by connorkrupp** [comment]
I'd like to have caching work reliably to support a client refetching like every 30 seconds or something, iOS checks for changes every time the view appears and we have a pretty good caching mechanism in place to support what I described above

**Comment by antoniomika** [comment]
That should be done with #8 and follow the authMiddleware with the auth group. I'm thinking of refactoring the middleware to `authMiddleware(groupName, authType, verifyEmail)`, where groupName defaults to `all`, `authType` defaults to `undefined` and `verifyEmail` defaults to `true`

**Comment by antoniomika** [comment]
Alright, we can do that for caching then. No models deleted, just modified.
