### ISSUE TITLE
Add web sockets to support chat system

### ISSUE THREAD

**Issue by connorkrupp** [mhacks/mhacks-web#111]
## Feature
https://faye.jcoglan.com/node.html
https://github.com/uWebSockets/uWebSockets
One channel + Direct messages
Hash of two people’s names to create private channel
Authentication
* Each message has to be checked on server before publishing to clients
* For DMs make sure they are allowed in
* Rate limiting - Rocket League style
* Use full names, or just first name + first letter name
* Mongo pagination
Need
* Endpoint for active users in chat
* Within users, need to know whether they are actually active
* ServiceWorker for background notifications

**Comment by antoniomika** [comment]
Opting to use https://github.com/deepstreamIO/deepstream.io for this. The pub/sub model as well as the performance seem to be solid.

**Comment by antoniomika** [comment]
Actually, deepstream has moved to a model where they want to be the main server. That doesn't really work well for our platform, so I'm falling back to https://socket.io/
