### ISSUE TITLE
Documentation for tooling

### ISSUE THREAD

**Issue by jeffchang5** [mhacks/mhacks-web#116]
I actually don't know how some of the tools work. A brief description would be nice :D

**Comment by antoniomika** [comment]
Could you describe what tooling you'd like more description of?

**Comment by jeffchang5** [comment]
Mostly just Travis and Prettier. However, describing the tooling for ESLint, the specific tools within Webpack, might help add verbosity when a person sets up the project.

**Comment by antoniomika** [comment]
Take a look [here](https://github.com/mhacks/mhacks-web/wiki/Contributing#testing-your-code-against-the-ci). It was already done in #102
