### ISSUE TITLE
Restructure Actions folder

### ISSUE THREAD

**Issue by roball24** [mhacks/mhacks-web#143]
### Expected function
module based folders
'module' >
    'requests.js'
    'pure.js'
    'thunks.js'

**Comment by roball24** [comment]
not urgent. I'll do this after the next deadline

**Comment by connorkrupp** [comment]
Each smart component folder should have its own:
* constants.js
* reducer.js
* sagas.js/thunks.js
* actions.js

Example:
```
profile/
    index.jsx
    constants.js
    actions.js
    reducer.js
    sagas.js or thunks.js
```

## constants.js
Namespaced action types:
```
export default {
    LOAD_PROFILE: 'mhacks/profile/LOAD_PROFILE'
}
```
I would create a factory method that you can import to do this automatically to have more of an interface like below which would automatically create the action types and you would only have to type them once
```
const actionTypes = [
    'LOAD_PROFILE'
];

export default createActionTypes('profile', actionTypes);
```

## actions.js
Nothing really changes here
```
    import {
        LOAD_PROFILE
    } from './constants';

    export function loadProfile(foo) {
        return {
            type: CHANGE_USERNAME,
            foo
  };
    
```

##reducer.js
Same as normal here

**Comment by connorkrupp** [comment]
the <App /> component would have its own folder with all those things for more global things. This whole thing would make it really easy for someone to extract a component out of our repo
