### ISSUE TITLE
Chat header wih lotsa names

### ISSUE THREAD

**Issue by SigmanZero** [mhacks/mhacks-web#226]
### Expected function
I think chat header should stick to being one line and maybe either just list number of people in the channel or cut off if the names list is too long - don't want the header to fill the entire container when we have hundreds of users
### Actual function
https://puu.sh/wq26k/66d639d34c.png

**Comment by connorkrupp** [comment]
Supposedly fixed

**Comment by connorkrupp** [comment]
Psych
