### ISSUE TITLE
Rename Application Model to HackerApplication

### ISSUE THREAD

**Issue by connorkrupp** [mhacks/mhacks-web#24]
## Reasoning

We've been doing this for years and I've been meaning to change it for a while. Application is a bit ambiguous in this context, especially since we have a MentorApplication model already

**Comment by connorkrupp** [comment]
@antoniomika @roball24 What do you think

**Comment by antoniomika** [comment]
This works for me. Let's just come up with a generic object that we can extend for both schemas. (i.e. we can just create a generic model `Application` that exports an object with the shared schemas for both mentors and hackers and extend them for the actual models)

**Comment by antoniomika** [comment]
Closed via #93
