### ISSUE TITLE
X Homepage FAQ Section

### ISSUE THREAD

**Issue by connorkrupp** [mhacks/mhacks-web#241]
As in design here https://drive.google.com/drive/u/1/folders/0B0t56npQW4JaZVhVMFNuS2Z4dlE
with content here: https://docs.google.com/a/umich.edu/document/d/1AyIzrNdt2Lh-OsnfgROQeHQ0Az2_at70celSQlhhyck/edit?usp=sharing

**Comment by cyanliu** [comment]
konor why is "international student" capitalized

**Comment by connorkrupp** [comment]
Made another issue #266 for capitalization issue @cyanliu
