### ISSUE TITLE
Location Model

### ISSUE THREAD

**Issue by connorkrupp** [mhacks/mhacks-web#267]
## Feature

* name: String
* latitude: String or Float (might want to research whats best)
* longitude: ^

**Comment by tarungog** [comment]
Looks like while mongodb supports floats natively, Mongoose doesn't. Will experiment with this:

https://www.npmjs.com/package/mongoose-double

We could also just use a string, but we'll probably end up doing more conversions than is ideal. In the past we used floats for lat/long
