### ISSUE TITLE
Application Page

### ISSUE THREAD

**Issue by cyanliu** [mhacks/mhacks-web#274]
Tiny views (like <480px) could probably use some padding around the entire window, and for whatever reason all of the form fields are centered and itty bitty (unnecessarily truncating some fields like in the Links section). The "Do you need travel reimbursement?" question has a tiny field too, causing the text to overlap with the dropdown arrows

The "application saved" toast appears behind the footer text for some reason, and if there are empty required fields, the error text is incredibly hard to read. (See also: screenshots)

![image](https://user-images.githubusercontent.com/11037821/28287082-f00f744c-6aff-11e7-89ee-0b307b0a4c43.png)
![image](https://user-images.githubusercontent.com/11037821/28287086-f47b82fa-6aff-11e7-92ba-4d24ea6bd099.png)

(I'm also 99% sure the menu says "Apply"/"Profile"/"Log Out" when there isn't an application on file, but then switches to "Application"/"Profile"/"Log Out" when there is; is this intended behavior?)

**Comment by connorkrupp** [comment]
Oh whoops I fixxed that a while ago I think
