### ISSUE TITLE
Mentor/Speaker confirmations

### ISSUE THREAD

**Issue by antoniomika** [mhacks/mhacks-web#307]
## Bug
Mentor/Speaker confirmations
### Expected function
Mentor/Speaker confirmations
### Actual function
Mentor/Speaker confirmations
### Steps to reproduce the bug
Mentor/Speaker confirmations

**Comment by SigmanZero** [comment]
This can probs just be the same as the hacker confirmation form if that makes things easier

**Comment by connorkrupp** [comment]
Decided to handle this manually
