### ISSUE TITLE
Adjust FAQ content

### ISSUE THREAD

**Issue by connorkrupp** [mhacks/mhacks-web#79]
## Remove

- [x] When are applications closing
- [x] How and when will I hear back
- [x] What If I'm a michigan student
- [x] Are you allowing walk ins
- [x] Will there be showers

## Edit

- [x] What happens if I'm accepted
- [x] Second Hacking section should say Logistics
- [x] Increase body font size by ~2px
- [ ] Add link to MHacks 9 schedule to first FAQ item
- [ ] Add link to MHacks 9 devpost to second FAQ item

**Comment by roball24** [comment]
checked changes on faq-fix branch

**Comment by connorkrupp** [comment]
"What happens if I'm accepted" is one of the questions in the Application section

The first FAQ item (what happens at a hackathon) should have a link to [here](https://drive.google.com/file/d/0B4fSxuPetYFGWjNLSng1QVdVdm8/view)

The second FAQ item (what do people normally make) should have a link [here](https://mhacks9.devpost.com/submissions)
