### ISSUE TITLE
Admin page

### ISSUE THREAD

**Issue by antoniomika** [mhacks/mhacks-web#9]
## Admin page
What needs to be implemented:
- Through middleware:
  - [ ] Verify user is admin
- In app:
  - [ ] Create an admin page template
  - [ ] List users show data as needed

**Comment by connorkrupp** [comment]
Not really sure how to label this until we break it up into smaller tasks haha

**Comment by connorkrupp** [comment]
I'm going to unassigned you @antoniomika since it's still in TODO and could possibly be picked up by someone else

**Comment by connorkrupp** [comment]
Scratch that, I'll let you untag yourself if you want to. I want people to be able to reserve tasks they want to take

**Comment by antoniomika** [comment]
This should be easy enough to do, it doesn't really require much since the models define the data. The frontend for this will be server rendered anyway, so there aren't really that many components that need to be worked out. I assigned myself because I pretty much took ownership of auth/initial user auth, so I figured this would be the final component for wrapping that all up.

**Comment by antoniomika** [comment]
This is done until next one?
